-- Admin-configurable username prefix for auto-approved referral registrations.
-- When set (e.g. "R"), new members get usernames R00001, R00002, ...
-- Leave empty for plain numeric sequence 00001, 00002, ...
ALTER TABLE referral_settings
  ADD COLUMN IF NOT EXISTS username_prefix TEXT NOT NULL DEFAULT '';
